/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    menu: Menu;
    pages: Page;
    posts: Post;
    categories: Category;
    testimonials: Testimonial;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    'global-cta': GlobalCta;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'global-cta': GlobalCtaSelect<false> | GlobalCtaSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: number;
  name: string;
  items?:
    | {
        label: string;
        type?: ('reference' | 'custom') | null;
        reference?:
          | ({
              relationTo: 'pages';
              value: number | Page;
            } | null)
          | ({
              relationTo: 'posts';
              value: number | Post;
            } | null);
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Określa TYLKO początkową zawartość przy tworzeniu strony — bloki nadal można dowolnie dodawać, usuwać, edytować i przestawiać. Wybór nie ma żadnego wpływu później (nic się nie synchronizuje ani nie nadpisuje).
   */
  template?: ('homepage' | 'text-page' | 'blank') | null;
  content?:
    | (
        | {
            tagline?: string | null;
            heading: string;
            description?: string | null;
            portrait?: (number | null) | Media;
            avatarsImage?: (number | null) | Media;
            /**
             * Pełne zdanie, np. "Trusted by 200+ businesses with reliable accounting and personal financial support."
             */
            trustText?: string | null;
            /**
             * Fragment powyższego tekstu do pogrubienia, np. "200+ businesses".
             */
            trustHighlight?: string | null;
            primaryButton: {
              label: string;
              type?: ('reference' | 'custom') | null;
              reference?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'posts';
                    value: number | Post;
                  } | null);
              url?: string | null;
            };
            secondaryButton: {
              label: string;
              type?: ('reference' | 'custom') | null;
              reference?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'posts';
                    value: number | Post;
                  } | null);
              url?: string | null;
            };
            floatingBadges?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            tagline?: string | null;
            heading: string;
            stats?:
              | {
                  value: string;
                  suffix?: string | null;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'trustStatementAndStatistics';
          }
        | {
            tagline?: string | null;
            heading: string;
            description?: string | null;
            /**
             * Niewymagane na poziomie zapisu (żeby dało się utworzyć stronę z szablonu bez realnego zdjęcia) — Astro renderuje sekcję poprawnie też bez niego, ale wizualnie brakuje wtedy zdjęcia w środkowej kolumnie.
             */
            image?: (number | null) | Media;
            painPoints?:
              | {
                  icon?: string | null;
                  iconImage?: (number | null) | Media;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            closingText?: string | null;
            button: {
              label: string;
              type?: ('reference' | 'custom') | null;
              reference?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'posts';
                    value: number | Post;
                  } | null);
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'painPoints';
          }
        | {
            tagline?: string | null;
            heading: string;
            description?: string | null;
            services?:
              | {
                  number: string;
                  title: string;
                  description: string;
                  areas?:
                    | {
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  /**
                   * Niewymagane na poziomie zapisu (żeby dało się utworzyć stronę z szablonu bez realnego zdjęcia) — Astro renderuje usługę poprawnie też bez niego.
                   */
                  image?: (number | null) | Media;
                  button: {
                    label: string;
                    type?: ('reference' | 'custom') | null;
                    reference?:
                      | ({
                          relationTo: 'pages';
                          value: number | Page;
                        } | null)
                      | ({
                          relationTo: 'posts';
                          value: number | Post;
                        } | null);
                    url?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            tagline?: string | null;
            heading: string;
            description?: string | null;
            /**
             * Niewymagane na poziomie zapisu (żeby dało się utworzyć stronę z szablonu bez realnego zdjęcia) — Astro renderuje sekcję poprawnie też bez niego.
             */
            image?: (number | null) | Media;
            features?:
              | {
                  icon?: string | null;
                  iconImage?: (number | null) | Media;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'personalRelationship';
          }
        | {
            tagline?: string | null;
            heading: string;
            /**
             * Niewymagane na poziomie zapisu (żeby dało się utworzyć stronę z szablonu bez realnego zdjęcia) — Astro renderuje sekcję poprawnie też bez niego.
             */
            portrait?: (number | null) | Media;
            bio?: string | null;
            facts?:
              | {
                  label: string;
                  type?: ('tags' | 'images') | null;
                  tags?:
                    | {
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  images?:
                    | {
                        image: number | Media;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            quote?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'experienceAndTrust';
          }
        | {
            tagline?: string | null;
            heading: string;
            description?: string | null;
            /**
             * Niewymagane na poziomie zapisu (żeby dało się utworzyć stronę z szablonu bez realnego zdjęcia) — Astro renderuje sekcję poprawnie też bez niego.
             */
            image?: (number | null) | Media;
            steps?:
              | {
                  step: string;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'onboardingProcess';
          }
        | {
            tagline?: string | null;
            heading: string;
            testimonialsMode?: ('latest' | 'manual') | null;
            manualTestimonials?: (number | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            tagline?: string | null;
            heading: string;
            description?: string | null;
            postsMode?: ('latest' | 'manual') | null;
            manualPosts?: (number | Post)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blog';
          }
        | {
            tagline?: string | null;
            heading: string;
            description?: string | null;
            button: {
              label: string;
              type?: ('reference' | 'custom') | null;
              reference?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'posts';
                    value: number | Post;
                  } | null);
              url?: string | null;
            };
            faqs?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            /**
             * Domyślnie ta sekcja pokazuje treść ustawioną w Ustawienia → CTA (globalny). Odznacz, żeby ustawić inną treść tylko dla tej strony.
             */
            useGlobal?: boolean | null;
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            /**
             * Niewymagane na poziomie zapisu (żeby dało się utworzyć stronę z szablonu bez realnego zdjęcia) — Astro renderuje sekcję poprawnie też bez niego.
             */
            backgroundImage?: (number | null) | Media;
            button?: {
              label: string;
              type?: ('reference' | 'custom') | null;
              reference?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'posts';
                    value: number | Post;
                  } | null);
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            tagline?: string | null;
            heading: string;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textPage';
          }
      )[]
    | null;
  /**
   * Nazwa używana tylko w panelu administracyjnym. Nie wyświetla się na stronie.
   */
  internalName: string;
  /**
   * Nazwa strony widoczna publicznie. Pojawia się w pasku tytułu przeglądarki oraz w wynikach wyszukiwania.
   */
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * Adres URL strony. Slug musi być unikalny w serwisie i powinien być krótki oraz czytelny. Strona główna serwisu ma slug "/".
   */
  slug: string;
  /**
   * Krótki opis (do ok. 155 znaków) używany w wynikach wyszukiwania oraz jako og:description/twitter:description.
   */
  metaDescription?: string | null;
  /**
   * Obraz pokazywany przy udostępnianiu linku (Facebook, LinkedIn, X/Twitter...). Zalecane min. 1200×630px.
   */
  ogImage?: (number | null) | Media;
  /**
   * Nadpisz canonical URL, jeśli ta sama treść ma być indeksowana pod innym adresem niż domyślny.
   */
  canonicalUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  category?: (number | null) | Category;
  excerpt?: string | null;
  featuredImage: number | Media;
  author?: string | null;
  publishedDate?: string | null;
  readTime?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Tytuł wpisu widoczny publicznie. Pojawia się w pasku tytułu przeglądarki oraz w wynikach wyszukiwania.
   */
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * Adres URL wpisu. Slug musi być unikalny w serwisie i powinien być krótki oraz czytelny.
   */
  slug: string;
  /**
   * Krótki opis (do ok. 155 znaków) używany w wynikach wyszukiwania oraz jako og:description/twitter:description.
   */
  metaDescription?: string | null;
  /**
   * Obraz pokazywany przy udostępnianiu linku (Facebook, LinkedIn, X/Twitter...). Zalecane min. 1200×630px.
   */
  ogImage?: (number | null) | Media;
  /**
   * Nadpisz canonical URL, jeśli ta sama treść ma być indeksowana pod innym adresem niż domyślny.
   */
  canonicalUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  heading?: string | null;
  description?: string | null;
  /**
   * Nazwa używana tylko w panelu administracyjnym. Nie wyświetla się na stronie.
   */
  internalName?: string | null;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * Adres URL kategorii. Slug musi być unikalny w serwisie i powinien być krótki oraz czytelny.
   */
  slug: string;
  /**
   * Krótki opis (do ok. 155 znaków) używany w wynikach wyszukiwania oraz jako og:description/twitter:description.
   */
  metaDescription?: string | null;
  /**
   * Obraz pokazywany przy udostępnianiu linku (Facebook, LinkedIn, X/Twitter...). Zalecane min. 1200×630px.
   */
  ogImage?: (number | null) | Media;
  /**
   * Nadpisz canonical URL, jeśli ta sama treść ma być indeksowana pod innym adresem niż domyślny.
   */
  canonicalUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  author: string;
  company?: string | null;
  rating: number;
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'menu';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  name?: T;
  items?:
    | T
    | {
        label?: T;
        type?: T;
        reference?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  template?: T;
  content?:
    | T
    | {
        hero?:
          | T
          | {
              tagline?: T;
              heading?: T;
              description?: T;
              portrait?: T;
              avatarsImage?: T;
              trustText?: T;
              trustHighlight?: T;
              primaryButton?:
                | T
                | {
                    label?: T;
                    type?: T;
                    reference?: T;
                    url?: T;
                  };
              secondaryButton?:
                | T
                | {
                    label?: T;
                    type?: T;
                    reference?: T;
                    url?: T;
                  };
              floatingBadges?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        trustStatementAndStatistics?:
          | T
          | {
              tagline?: T;
              heading?: T;
              stats?:
                | T
                | {
                    value?: T;
                    suffix?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        painPoints?:
          | T
          | {
              tagline?: T;
              heading?: T;
              description?: T;
              image?: T;
              painPoints?:
                | T
                | {
                    icon?: T;
                    iconImage?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              closingText?: T;
              button?:
                | T
                | {
                    label?: T;
                    type?: T;
                    reference?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              tagline?: T;
              heading?: T;
              description?: T;
              services?:
                | T
                | {
                    number?: T;
                    title?: T;
                    description?: T;
                    areas?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    image?: T;
                    button?:
                      | T
                      | {
                          label?: T;
                          type?: T;
                          reference?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        personalRelationship?:
          | T
          | {
              tagline?: T;
              heading?: T;
              description?: T;
              image?: T;
              features?:
                | T
                | {
                    icon?: T;
                    iconImage?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        experienceAndTrust?:
          | T
          | {
              tagline?: T;
              heading?: T;
              portrait?: T;
              bio?: T;
              facts?:
                | T
                | {
                    label?: T;
                    type?: T;
                    tags?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    images?:
                      | T
                      | {
                          image?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              quote?: T;
              id?: T;
              blockName?: T;
            };
        onboardingProcess?:
          | T
          | {
              tagline?: T;
              heading?: T;
              description?: T;
              image?: T;
              steps?:
                | T
                | {
                    step?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              tagline?: T;
              heading?: T;
              testimonialsMode?: T;
              manualTestimonials?: T;
              id?: T;
              blockName?: T;
            };
        blog?:
          | T
          | {
              tagline?: T;
              heading?: T;
              description?: T;
              postsMode?: T;
              manualPosts?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              tagline?: T;
              heading?: T;
              description?: T;
              button?:
                | T
                | {
                    label?: T;
                    type?: T;
                    reference?: T;
                    url?: T;
                  };
              faqs?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              useGlobal?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              backgroundImage?: T;
              button?:
                | T
                | {
                    label?: T;
                    type?: T;
                    reference?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        textPage?:
          | T
          | {
              tagline?: T;
              heading?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  internalName?: T;
  title?: T;
  generateSlug?: T;
  slug?: T;
  metaDescription?: T;
  ogImage?: T;
  canonicalUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  category?: T;
  excerpt?: T;
  featuredImage?: T;
  author?: T;
  publishedDate?: T;
  readTime?: T;
  content?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  title?: T;
  generateSlug?: T;
  slug?: T;
  metaDescription?: T;
  ogImage?: T;
  canonicalUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  internalName?: T;
  name?: T;
  generateSlug?: T;
  slug?: T;
  metaDescription?: T;
  ogImage?: T;
  canonicalUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  company?: T;
  rating?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Domyślny tytuł strony (<title>) i og:site_name, gdy konkretna podstrona nie ma własnego tytułu. Zasila też pole "name" w danych strukturalnych (JSON-LD) w zakładce Organization.
   */
  siteName: string;
  /**
   * Domyślny meta description, gdy konkretna podstrona nie ma własnego opisu. Zasila też pola "slogan"/"description" w danych strukturalnych (JSON-LD) w zakładce Organization.
   */
  tagline?: string | null;
  /**
   * Ikona wyświetlana w karcie przeglądarki. Zalecany kwadratowy PNG lub SVG.
   */
  favicon?: (number | null) | Media;
  blog?: {
    /**
     * Wyświetlany jako tagline nad nagłówkiem na liście wpisów (/blog) oraz na stronach kategorii.
     */
    blogTitle?: string | null;
    /**
     * Ile wpisów pokazuje się od razu na /blog i na stronach kategorii, zanim trzeba kliknąć "Load More".
     */
    postsPerPage?: number | null;
  };
  /**
   * Krótkie napisy "na sztywno" w kodzie strony (etykiety przycisków, nagłówki pomocnicze) — nie należą do żadnego konkretnego bloku, więc zebrane są tutaj w jednym miejscu do tłumaczenia/edycji.
   */
  interfaceText?: {
    hero?: {
      scrollDownLabel?: string | null;
    };
    services?: {
      areasOfSupportLabel?: string | null;
    };
    blog?: {
      readArticleLabel?: string | null;
      loadMoreLabel?: string | null;
    };
    post?: {
      faqHeading?: string | null;
      backButtonLabel?: string | null;
      tableOfContentsHeading?: string | null;
    };
    breadcrumbHomeLabel?: string | null;
  };
  notFound?: {
    /**
     * Np. "Błąd 404".
     */
    tagline?: string | null;
    heading?: string | null;
    description?: string | null;
    button?: {
      label?: string | null;
      type?: ('reference' | 'custom') | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null);
      url?: string | null;
    };
    /**
     * Zawsze dokładnie 3 — ich pozycje na tle sekcji są ustalone na sztywno w kodzie, edytowalny jest tylko tekst.
     */
    badges?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  organization?: {
    /**
     * Używane w JSON-LD organizacji (schema.org "logo"). Zalecany kwadratowy/poziomy PNG lub SVG na jasnym tle.
     */
    logo?: (number | null) | Media;
    /**
     * Np. "Jan Kowalski Usługi Księgowe" — jeśli inna niż nazwa marketingowa (Nazwa strony/firmy w zakładce Ogólne).
     */
    legalName?: string | null;
    /**
     * Inne nazwy, pod którymi firma jest rozpoznawana (skróty, wersja bez polskich znaków...). Trafiają do JSON-LD jako "alternateName" — pomaga wyszukiwarkom łączyć różne warianty nazwy z tą samą firmą.
     */
    alternateName?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Trafia do danych strukturalnych (JSON-LD) jako "taxID" — standardowe pole dla polskich firm.
     */
    taxId?: string | null;
    /**
     * Trafia do danych strukturalnych (JSON-LD) jako identyfikator firmy ("identifier").
     */
    registrationNumber?: string | null;
    /**
     * Trafia do danych strukturalnych (JSON-LD) jako "foundingDate".
     */
    foundingDate?: string | null;
    /**
     * Realni właściciele/założyciele firmy — nie wymyślać. Trafiają do danych strukturalnych (JSON-LD) jako "founder".
     */
    founders?:
      | {
          givenName: string;
          familyName: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Trafia do danych strukturalnych (JSON-LD) jako "telephone". To NIE to samo pole co telefon w stopce (Footer → Dane kontaktowe) — tamten jest wyświetlany na stronie, ten tylko w JSON-LD. Wpisz oba, jeśli mają być spójne.
     */
    phone?: string | null;
    /**
     * Trafia do danych strukturalnych (JSON-LD) jako "email". To NIE to samo pole co e-mail w stopce (Footer → Dane kontaktowe) — analogicznie jak telefon.
     */
    email?: string | null;
    /**
     * Ustrukturyzowany adres pod JSON-LD (schema.org PostalAddress).
     */
    address?: {
      streetAddress?: string | null;
      addressLocality?: string | null;
      addressRegion?: string | null;
      postalCode?: string | null;
      addressCountry?: string | null;
    };
    /**
     * Realne URL-e profili (Facebook, Instagram, LinkedIn...) — trafiają do JSON-LD organizacji jako "sameAs". To NIE to samo co kolumna "Social Media" w stopce (tamta to menu nawigacyjne, może mieć placeholdery).
     */
    socialProfiles?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Logo w nagłówku strony. Jeśli puste, używane jest domyślne logo z kodu.
   */
  logo?: (number | null) | Media;
  /**
   * Adres, na który przechodzi kliknięcie w logo. Domyślnie strona główna ("/").
   */
  logoLink?: string | null;
  mainMenu?: (number | null) | Menu;
  cta: {
    label: string;
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  contact?: {
    address?: {
      label?: string | null;
      value?: string | null;
    };
    phone?: {
      label?: string | null;
      value?: string | null;
    };
    email?: {
      label?: string | null;
      value?: string | null;
    };
    hours?: {
      label?: string | null;
      value?: string | null;
    };
  };
  linkColumns?:
    | {
        title: string;
        menu: number | Menu;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  legalMenu?: (number | null) | Menu;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Domyślna treść bloku CTA — używana wszędzie tam, gdzie blok CTA na stronie ma włączone "Użyj globalnych ustawień".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-cta".
 */
export interface GlobalCta {
  id: number;
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  backgroundImage?: (number | null) | Media;
  button: {
    label: string;
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  favicon?: T;
  blog?:
    | T
    | {
        blogTitle?: T;
        postsPerPage?: T;
      };
  interfaceText?:
    | T
    | {
        hero?:
          | T
          | {
              scrollDownLabel?: T;
            };
        services?:
          | T
          | {
              areasOfSupportLabel?: T;
            };
        blog?:
          | T
          | {
              readArticleLabel?: T;
              loadMoreLabel?: T;
            };
        post?:
          | T
          | {
              faqHeading?: T;
              backButtonLabel?: T;
              tableOfContentsHeading?: T;
            };
        breadcrumbHomeLabel?: T;
      };
  notFound?:
    | T
    | {
        tagline?: T;
        heading?: T;
        description?: T;
        button?:
          | T
          | {
              label?: T;
              type?: T;
              reference?: T;
              url?: T;
            };
        badges?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  organization?:
    | T
    | {
        logo?: T;
        legalName?: T;
        alternateName?:
          | T
          | {
              value?: T;
              id?: T;
            };
        taxId?: T;
        registrationNumber?: T;
        foundingDate?: T;
        founders?:
          | T
          | {
              givenName?: T;
              familyName?: T;
              id?: T;
            };
        phone?: T;
        email?: T;
        address?:
          | T
          | {
              streetAddress?: T;
              addressLocality?: T;
              addressRegion?: T;
              postalCode?: T;
              addressCountry?: T;
            };
        socialProfiles?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  logoLink?: T;
  mainMenu?: T;
  cta?:
    | T
    | {
        label?: T;
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        address?:
          | T
          | {
              label?: T;
              value?: T;
            };
        phone?:
          | T
          | {
              label?: T;
              value?: T;
            };
        email?:
          | T
          | {
              label?: T;
              value?: T;
            };
        hours?:
          | T
          | {
              label?: T;
              value?: T;
            };
      };
  linkColumns?:
    | T
    | {
        title?: T;
        menu?: T;
        id?: T;
      };
  copyrightText?: T;
  legalMenu?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-cta_select".
 */
export interface GlobalCtaSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  backgroundImage?: T;
  button?:
    | T
    | {
        label?: T;
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}