
services:
  payload:
    image: node:22-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      - postgres
    env_file:
      - .env

  # Ensure your DATABASE_URL uses 'postgres' as the hostname ie. postgres://payload:payload@postgres:5432/payload
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
      POSTGRES_DB: payload
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: none

volumes:
  pgdata:
  node_modules:
